title: John Wong # your name (or website title) here
logo: # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research Analyst at the <a href="https://taxpolicycenter.org/author/john-wong">Urban-Brookings Tax Policy Center</a>.
  <br><br>
  Estimates featured in <a href="https://www.americanprogress.org/article/trump-administration-tariffs-could-result-in-450000-fewer-new-homes-through-2030/">Center for American Progress</a>, <a href="https://www.wsj.com/economy/trade/chinas-exports-rebound-in-november-97f24e06?st=mnKose&reflink=desktopwebshare_permalink">Wall Street Journal</a>, <a href="https://www.politifact.com/article/2025/nov/10/Trump-tariff-dividend-2000-stimulus/">Politifact</a>, <a href="https://www.datawrapper.de">Datawrapper</a>.
  <br><br>
  Jump to:<br>
  1. <a href="#microsimulation">Microsimulation</a><br>
  2. <a href="#blogs">Blogs</a>
  3. <a href="#working-papers">Working Papers</a><br>
  <br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-CXRL3XP9BW # your Google Analytics tracking ID here
